name: alarmsAndAnalytics
description: "alarmsAndAnalytics"
display-name: "alarmsAndAnalytics"
namespace: com.acme.stylebooks
schema-version: "1.0"
version: "0.1"
import-stylebooks:
  -
    namespace: netscaler.nitro.config
    prefix: ns
    version: "10.5"
parameters:
  -
    name: cs-params
    type: object
    required: true
    parameters:
      -
        name: csname
        type: string
        required: true
      -
        name: vip
        type: ipaddress
        required: true
  -
    name: appflowfilter
    type: string
    required: true
  -
    name: emailprofile
    type: string
    required: true
  -
    name: period
    type: string
    required: true
  -
    name: vip-params
    type: object[]
    required: true
    parameters:
      -
        name: lbname
        type: string
        required: true
      -
        name: vip
        type: ipaddress
        required: true
      -
        name: lbmethod
        type: string
        required: true
  -
    name: vip-params1
    type: object[]
    required: true
    parameters:
      -
        name: lbname
        type: string
        required: true
      -
        name: vip
        type: ipaddress
        required: true
      -
        name: lbmethod
        type: string
        required: true
substitutions:
  analytics_object_cstype: csvserver
  analytics_object_lbtype: lbvserver
components:
  -
    name: my-csvserver-comp
    type: ns::csvserver
    properties:
      name: $parameters.cs-params.csname
      servicetype: HTTP
      ipv46: $parameters.cs-params.vip
      port: 80
  -
    name: my-lbvserver-comp
    type: ns::lbvserver
    repeat: $parameters.vip-params
    repeat-item: vs
    properties:
      name: $vs.lbname
      servicetype: HTTP
      ipv46: $vs.vip
      port: 80
      lbmethod: $vs.lbmethod
  -
    name: my-lbvserver-comp1
    type: ns::lbvserver
    repeat: $parameters.vip-params1
    repeat-item: vs1
    properties:
      name: $vs1.lbname
      servicetype: HTTP
      ipv46: $vs1.vip
      port: 80
      lbmethod: $vs1.lbmethod
outputs:
  -
    name: mycs
    value: $components.my-csvserver-comp
  -
    name: mylbs
    value: $components.my-lbvserver-comp
  -
    name: mylbs1
    value: $components.my-lbvserver-comp1
operations:
  analytics:
    -
      name: csvserver-op
      properties:
        target: $outputs.mycs
        filter: $parameters.appflowfilter
    -
      name: lbvserver-op
      repeat: $outputs.mylbs
      repeat-item: lb
      repeat-condition: $lb.properties.name != "test1"
      properties:
        target: $lb
        filter: "true"
    -
      name: lbvserver-op1
      repeat: $outputs.mylbs1
      repeat-item: lb1
      repeat-condition: $lb1.properties.name != "test1"
      properties:
        target: $lb1
        filter: "true"
  alarms:
  -
    name: csvserver_alarm
    repeat: $outputs.mylbs
    repeat-item: lb1
    properties:
      target: $lb1
      email-profile: $parameters.emailprofile
      sms-profile: "NetScalerSMS"
      rules:
        -
          period-unit: $parameters.period
          metric: "total_requests"
          operator: "greaterthan"
          value: 25
        -
          period-unit: "day"
          metric: "total_bytes"
          operator: "lessthan"
          value: 60
  -
    name: lbvserver_alarm
    repeat: $outputs.mylbs
    repeat-item: lb
    properties:
      target: $outputs.mycs
      email-profile: $parameters.emailprofile
      sms-profile: "NetScalerSMS"
      rules:
        -
          period-unit: $parameters.period
          metric: "total_requests"
          operator: "greater"
          value: 25
        -
          period-unit: "day"
          metric: "total_bytes"
          operator: "less"
          value: 60
  -
    name: lbvserver_alarm1
    repeat: $outputs.mylbs1
    repeat-item: lb2
    properties:
      target: $lb2
      email-profile: $parameters.emailprofile
      sms-profile: "NetScalerSMS"
      rules:
        -
          period-unit: $parameters.period
          metric: "total_requests"
          operator: "greater"
          value: 25
        -
          period-unit: "day"
          metric: "total_bytes"
          operator: "less"
          value: 60