--- 
name: sample-vpn-config
namespace: com.acme-corp.adc.stylebooks
version: "1.0"
description: |
    This StyleBook shows an example of a VPN Configuration that uses 
    authorization and session policies and configures an IntranetApplication
schema-version: "1.0"
import-stylebooks: 
    - 
        namespace: netscaler.nitro.config
        version: "10.5"
        prefix: ns
parameters:
    -
        name: vpn-name
        label: Name of VPN
        description: "A Name that represents this VPN"
        type: string    
        required: true
    -
        name: vpn-ip
        label: VPN IP Address
        description: "The virtual IP address that represents the VPN to which users will connect and authenticate"
        type: ipaddress    
        required: true
    -
        name: vpn-port
        label: VPN Port
        description: "The TCP port of the VPN IP address"
        type: tcp-port
        default: 443    
    -
        name: vpn-max-users
        label: "VPN Maximum Users"
        description: "The Maximum number of Users allowed to connect to the VPN"
        type: number
        min-value: 1
        max-value: 100
        default: 5
    -
        name: vpn-users
        label: "VPN Users"
        description: "List of VPN Users"
        type: object[]
        required: true
        parameters:
            -
                name: username
                label: Username
                description: "The username of the VPN user"
                type: string
                required: true
            -
                name: password
                label: Password
                description: "The password of the VPN user"
                type: password
                required: true
    -
        name: groupname
        label: Groupname
        description: "The group name to which the VPN users will belong"
        type: string
        required: true
    -
        name: intranetApp-ip
        label: VPN IntranetApp IP
        description: "The IP address of the Intranet Application or subnet to make available through the VPN"
        type: ipaddress
        required: true
    -
        name: intranetApp-netmask
        label: VPN IntranetApp Netmask
        description: "The IP address of the Intranet Application or subnet to make available through the VPN"
        type: ipaddress    
        default: "255.255.255.0"
    -
        name: vpn-session-timeout
        label: VPN Session Timeout (minutes)
        description: "The time (in minutes) of inactivity after which the VPN session times out"
        type: number
        default: 10
components:
    -
        name: vpn-vserver-comp
        type: ns::vpnvserver
        description: |
            This StyleBook component creates a Nitro configuration object for the VPN VServer
        properties:
            name: $parameters.vpn-name
            servicetype: SSL
            ipv46: $parameters.vpn-ip
            port: str($parameters.vpn-port)
            maxAAAUsers: $parameters.vpn-max-users
    -
        name: group-comp
        type: ns::aaagroup
        description: |
            This StyleBook component creates the Nitro configuration object for AAA Group
        properties:
            groupname: $parameters.groupname
    -
        name: user-comp
        type: ns::aaauser
        description: |
            This StyleBook component creates the Nitro configuration object for each AAA user
            given in the parameters
        repeat: $parameters.vpn-users
        repeat-item: vpn-user
        properties:
            username: $vpn-user.username
            password: $vpn-user.password
        components:
            -
                name: user-group-binding-comp
                type: ns::aaagroup_aaauser_binding
                description: |
                    This StyleBook sub-component creates a configuration object that binds the
                    current aaa user configuration object created by the parent component to the aaa group
                    created by the component called group-comp
                properties:
                    username: $parent.properties.username
                    groupname: $components.group-comp.properties.groupname
    -
        name: vpn-intranetapp-comp
        type: ns::vpnIntranetApplication
        description: |
            This StyleBook component creates the Nitro configuration object for the 
            Intranet subnet that will be accessible through the VPN
        properties:
            intranetApplication: $parameters.vpn-name + "-" + "intranetapp"
            protocol: ANY
            destip: $parameters.intranetApp-ip
            netmask: $parameters.intranetApp-netmask
            destport: str("1-65535")
            interception: TRANSPARENT
    -
        name: authz-policy-comp
        type: ns::authorizationpolicy
        description: |
            This StyleBook component creates a Nitro configuration object for the VPN authorization
            policy that allows access to the configured subnet
        properties:
            name: $parameters.vpn-name + "-" + "vpn-authzpol"
            rule: REQ.IP.DESTIP + " == " + str($parameters.intranetApp-ip) + " -netmask " + str($parameters.intranetApp-netmask)
            action: ALLOW
    -
        name: vpn-sessionaction-comp
        type: ns::vpnsessionaction
        description: |
            This StyleBook component creates a Nitro configuration object for the VPN Session Action
        properties:
            name: $parameters.vpn-name + "-" + "vpn-sessionaction"
            windowsClientType: AGENT
            defaultAuthorizationAction: ALLOW
            homepage: none
            icaProxy: "OFF"
            forceCleanup: all
            clientCleanupPrompt: "OFF"
            transparentInterception: "ON"
            splitTunnel: "ON"
            sessTimeout: $parameters.vpn-session-timeout
    -
        name: vpn-sessionpolicy-comp
        type: ns::vpnsessionpolicy
        description: |
            This StyleBook component creates a Nitro configuration object for the VPN Session Policy
        properties:
            name: $parameters.vpn-name + "-" + "vpn-sessionpolicy"
            rule: "ns_true"
            action: $components.vpn-sessionaction-comp.properties.name
    -
        name: vpn-aaagroup-sessionpolicy-binding-comp
        type: ns::aaagroup_vpnsessionpolicy_binding
        description: |
            This StyleBook component creates a Nitro configuration object that binds 
            the VPN Session Policy to the AAA Group
        properties:
            groupname: $components.group-comp.properties.groupname
            policy: $components.vpn-sessionpolicy-comp.properties.name
    -
        name: vpn-aaagroup-authzpolicy-binding-comp
        type: ns::aaagroup_authorizationpolicy_binding
        description: |
            This StyleBook component creates a Nitro configuration object that binds 
            the VPN Authorization Policy to the AAA Group
        properties:
            groupname: $components.group-comp.properties.groupname
            policy: $components.authz-policy-comp.properties.name
    -
        name: vpn-aaagroup-intranetip-binding-comp
        type: ns::aaagroup_intranetip_binding
        description: |
            This StyleBook component creates a Nitro configuration object that binds 
            the Intranet subnet (intranetip/netmask) to the AAA Group
        properties:
            groupname: $components.group-comp.properties.groupname
            intranetip: $parameters.intranetApp-ip
            netmask: $parameters.intranetApp-netmask
    -
        name: vpn-aaagroup-intranetapp-binding-comp
        type: ns::aaagroup_vpnintranetapplication_binding
        description: |
            This StyleBook component creates a Nitro configuration object that binds 
            the Intranet Application created earlier to the AAA Group
        properties:
            groupname: $components.group-comp.properties.groupname
            intranetapplication: $components.vpn-intranetapp-comp.properties.intranetApplication

